@extends('layouts.base.layout')
@section('header')
    @include('layouts.base.header')
@endsection
@section('content')
    @include('base.section.blog-post')
@endsection
@section('footer')
    @include('layouts.base.footer')
@endsection
