@extends('layouts.user.layout')
@section('header')
    @include('layouts.user.header')
@endsection
@section('left_sidebar')
    @include('layouts.user.left_sidebar')
@endsection
@section('right_sidebar')
    @include('layouts.common_element.right_sidebar')
@endsection
@section('breadcrumb')
    @include('layouts.user.breadcrumb')
@endsection
@section('content')
    @include('user.section.free-courses.article')
@endsection
@section('footer')
    @include('layouts.common_element.footer')
@endsection
@section('demo-options')
    @include('layouts.user.demo-option')
@endsection
